package SpringBootFirstProject.example.AkashSpringBoot.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

//@Entity → DB table

@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor


public class User {
    //     how to generate values for the primary key field marked with @Id.

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;   // Primary key, auto-generated by DB (auto-increment)

    private String name;   // No constraints → can be null, can have duplicates

    @Column(unique = true, nullable = false)
    private String email;  // Must be unique, cannot be null

    @Column(nullable = false)
    private String password; // Cannot be null, but duplicates allowed
}

